### ISSUE TITLE
Linux 4.13: call to ‘__read_overflow2’ declared with attribute error: detected read beyond size of object passed as 2nd parameter

### ISSUE THREAD

**Issue by k0ste** [vel21ripn/nDPI#27] opened 2017-10-31 16:05 UTC
AFAIK this occurs when kernel builded with enabled `FORTIFY_SOURCE`.

```shell
[k0ste@WorkStation tmp]$ git clone git@github.com:vel21ripn/nDPI.git ipt_ndpi
Cloning into 'ipt_ndpi'...
remote: Counting objects: 8231, done.
remote: Total 8231 (delta 0), reused 0 (delta 0), pack-reused 8231
Receiving objects: 100% (8231/8231), 23.55 MiB | 480.00 KiB/s, done.
Resolving deltas: 100% (5484/5484), done.
[k0ste@WorkStation tmp]$ cd ipt_ndpi/
[k0ste@WorkStation ipt_ndpi]$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:7: installing './compile'
configure.ac:7: installing './config.guess'
configure.ac:7: installing './config.sub'
configure.ac:5: installing './install-sh'
configure.ac:5: installing './missing'
example/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for pcap_open_live in -lpcap... yes
Package json-c was not found in the pkg-config search path.
Perhaps you should add the directory containing `json-c.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json-c' found
Package json-c was not found in the pkg-config search path.
Perhaps you should add the directory containing `json-c.pc'
to the PKG_CONFIG_PATH environment variable
No package 'json-c' found
checking for NT_Init in -lntapi... no
checking for json_object_new_object in -ljson-c... no
checking for pthread_setaffinity_np in -lpthread... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/lib/Makefile
config.status: creating example/Makefile
config.status: creating libndpi.pc
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
[k0ste@WorkStation ipt_ndpi]$ cd ndpi-netfilter/
[k0ste@WorkStation ndpi-netfilter]$ make
```
```python
make -C ipt
make[1]: Entering directory '/tmp/ipt_ndpi/ndpi-netfilter/ipt'
cc -fPIC -I../include -I../lib -I../src -DOPENDPI_NETFILTER_MODULE -O2 -Wall -D_INIT=libxt_ndpi_init -c -o libxt_ndpi.o libxt_ndpi.c;
cc -shared -o libxt_ndpi.so libxt_ndpi.o;
rm libxt_ndpi.o
make[1]: Leaving directory '/tmp/ipt_ndpi/ndpi-netfilter/ipt'
make -C src
make[1]: Entering directory '/tmp/ipt_ndpi/ndpi-netfilter/src'
make -j 4 -C /lib/modules/4.13.9-1-ARCH/build M=$PWD modules -w;
make[2]: Entering directory '/usr/lib/modules/4.13.9-1-ARCH/build'
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/main.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/../third_party/src/node.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/../third_party/src/ahocorasick.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/ndpi_main.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/afp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/aimini.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/applejuice.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/armagetron.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/ayiya.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/battlefield.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/bgp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/bittorrent.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/citrix.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/ciscovpn.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/collectd.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/corba.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/crossfire.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/csgo.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/dcerpc.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/dhcp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/dhcpv6.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/directconnect.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/directdownloadlink.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/dns.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/dofus.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/dropbox.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/eaq.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/edonkey.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/fasttrack.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/fiesta.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/filetopia.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/florensia.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/ftp_control.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/ftp_data.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/gnutella.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/gtp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/guildwars.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/h323.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/halflife2_and_mods.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/http.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/http_activesync.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/iax.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/icecast.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/imesh.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/ipp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/irc.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/jabber.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/kakaotalk_voice.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/kerberos.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/kontiki.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/ldap.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/lotus_notes.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/mail_imap.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/mail_pop.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/mail_smtp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/maplestory.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/mdns.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/meebo.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/mgcp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/mms.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/mpegts.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/msn.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/mssql.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/mysql.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/netbios.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/netflow.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/nfs.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/noe.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/non_tcp_udp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/ntp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/openft.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/openvpn.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/oracle.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/oscar.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/pando.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/megaco.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/pcanywhere.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/postgres.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/pplive.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/ppstream.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/pptp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/qq.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/quake.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/quic.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/radius.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/rdp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/redis_net.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/rsync.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/rtp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/rtcp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/rtmp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/rtsp.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/sflow.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/shoutcast.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/sip.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/skinny.o
  CC [M]  /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/skype.o
In file included from ./include/linux/bitmap.h:8:0,
                 from ./include/linux/cpumask.h:11,
                 from ./include/linux/mm_types_task.h:13,
                 from ./include/linux/mm_types.h:4,
                 from ./include/linux/kmemcheck.h:4,
                 from ./include/linux/skbuff.h:18,
                 from ./include/linux/ip.h:20,
                 from /tmp/ipt_ndpi/ndpi-netfilter/src/../include/ndpi_unix.h:47,
                 from /tmp/ipt_ndpi/ndpi-netfilter/src/../include/ndpi_main.h:66,
                 from /tmp/ipt_ndpi/ndpi-netfilter/src/../include/ndpi_api.h:29,
                 from /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/sip.c:26:
In function ‘memcmp’,
    inlined from ‘ndpi_search_sip_handshake’ at /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/sip.c:124:10,
    inlined from ‘ndpi_search_sip.part.0’ at /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/sip.c:189:7,
    inlined from ‘ndpi_search_sip’:
./include/linux/string.h:346:4: error: call to ‘__read_overflow2’ declared with attribute error: detected read beyond size of object passed as 2nd parameter
    __read_overflow2();
    ^~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:302: /tmp/ipt_ndpi/ndpi-netfilter/src/../lib/protocols/sip.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:1512: _module_/tmp/ipt_ndpi/ndpi-netfilter/src] Error 2
make[2]: Leaving directory '/usr/lib/modules/4.13.9-1-ARCH/build'
make[1]: *** [Makefile:165: modules] Error 2
make[1]: Leaving directory '/tmp/ipt_ndpi/ndpi-netfilter/src'
make: *** [Makefile:3: all] Error 2
```

**Comment by vel21ripn** [comment] 2017-10-31 17:17
What version of gcc is used for building?

**Comment by vel21ripn** [comment] 2017-10-31 18:17
What gcc version is used ?
I can't reproduce error  using gcc version 5.3.0 and kernel 4.13.10

**Comment by k0ste** [comment] 2017-11-01 00:38
7.2.0

**Comment by vel21ripn** [comment] 2017-11-01 08:55
```[k0ste@WorkStation tmp]$ git clone git@github.com:vel21ripn/nDPI.git ipt_ndpi```
This is ndpi-1.7.0!
Fixed in https://github.com/vel21ripn/nDPI/commit/0670f78b909ad4cffea8f58d6d66a51810dd9368

**Closed as completed by vel21ripn** 2017-11-01 08:55 UTC

**Comment by k0ste** [comment] 2017-11-01 09:29
>  This is ndpi-1.7.0!

Yep, I didn't switch branch.
AFAIK `netfilter` branch is not stable yet/have performance issues.

upd: fix works.
